# Generated by Django 5.1.7 on 2025-03-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcompletion',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='easter.step'),
        ),
    ]
