# Generated by Django 5.1.7 on 2025-03-27 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easter', '0002_alter_stepcompletion_step'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Egg',
        ),
        migrations.CreateModel(
            name='EggCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('egg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='easter.egg')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('person', 'egg')},
            },
        ),
        migrations.DeleteModel(
            name='StepCompletion',
        ),
    ]
