# Generated by Django 5.1.7 on 2025-03-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easter', '0003_rename_step_egg_eggcompletion_delete_stepcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='egghunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eggs', to='easter.egghunt'),
        ),
    ]
